"""onboarding_sessions

Revision ID: 5d1d9cd80e8b
Revises: 35ae5b71a493
Create Date: 2026-04-27 06:46:01.295074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d1d9cd80e8b'
down_revision: Union[str, None] = '35ae5b71a493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wa_chat_id', sa.String(length=128), nullable=False),
    sa.Column('phone_e164', sa.String(length=24), nullable=False),
    sa.Column('state', sa.Enum('ask_name', 'ask_business', 'ask_address', 'ask_email', 'ask_plan', 'ask_billing', 'payment_sent', name='onboarding_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wa_chat_id', name='uq_onboarding_sessions_wa_chat_id')
    )
    op.create_index(op.f('ix_onboarding_sessions_phone_e164'), 'onboarding_sessions', ['phone_e164'], unique=False)
    op.create_index(op.f('ix_onboarding_sessions_state'), 'onboarding_sessions', ['state'], unique=False)
    op.create_index(op.f('ix_onboarding_sessions_tenant_id'), 'onboarding_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_onboarding_sessions_user_id'), 'onboarding_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_onboarding_sessions_wa_chat_id'), 'onboarding_sessions', ['wa_chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_sessions_wa_chat_id'), table_name='onboarding_sessions')
    op.drop_index(op.f('ix_onboarding_sessions_user_id'), table_name='onboarding_sessions')
    op.drop_index(op.f('ix_onboarding_sessions_tenant_id'), table_name='onboarding_sessions')
    op.drop_index(op.f('ix_onboarding_sessions_state'), table_name='onboarding_sessions')
    op.drop_index(op.f('ix_onboarding_sessions_phone_e164'), table_name='onboarding_sessions')
    op.drop_table('onboarding_sessions')
    # ### end Alembic commands ###
